In [3]:
import torch


## Scalar

In [4]:
scalar_value = 42
# generate 0 dimensional tensor
scalar_tensor =torch.tensor(scalar_value)

In [5]:
scalar_tensor

tensor(42)

In [6]:
scalar_tensor.shape

torch.Size([])

## Vectors

In [8]:
v = torch.tensor([1, 2, 3])

In [9]:
v

tensor([1, 2, 3])

In [10]:
v = torch.zeros(3)

In [11]:
v

tensor([0., 0., 0.])

In [14]:
v = torch.ones(5)

In [15]:
v

tensor([1., 1., 1., 1., 1.])

In [16]:
v1 = torch.zeros(5)
v2 = torch.ones(5)

In [17]:
print(v1," ", v2)

tensor([0., 0., 0., 0., 0.])   tensor([1., 1., 1., 1., 1.])


In [19]:
v3 = v1 + v2
print(v3)

tensor([1., 1., 1., 1., 1.])


In [20]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
v3 = v1 + v2
print(v3)

tensor([5, 7, 9])


In [22]:
v = torch.tensor([1, 2, 3, 4])
s = torch.sum(v)
print(s)

tensor(10)


In [29]:
v = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8,9,10])
print(v)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [30]:
print(v[2])

tensor(3)


In [31]:
print(v[:4])

tensor([1, 2, 3, 4])


In [33]:
print(v[4:])

tensor([ 5,  6,  7,  8,  9, 10])


In [34]:
print(v[4:8])

tensor([5, 6, 7, 8])


## Matrix

In [36]:
m = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(m)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [39]:
m_0 = torch.zeros(3, 3, dtype=torch.float32)
print(m_0)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [40]:
m_1 = torch.ones(2, 4, dtype=torch.float32)
print(m_1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [46]:
# Create two 2X3 matcies and perfmorm matrix addition
m1 = torch.tensor([[1, 2, 3], [4 ,5, 6]])
m2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

print(m1.shape , " ", m2.shape)

m3 = m1 + m2

print(m1)
print(m2)
print(m3)


torch.Size([2, 3])   torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 8, 10, 12],
        [14, 16, 18]])


In [48]:
m1 = torch.tensor([[1, 2, 3], [4, 5, 6 ]])  # 2x3 matrix
m2 = torch.tensor([[7, 8], [9, 10], [11, 12]]) # 3x2 matrix
m3 = torch.mm(m1, m2)  # 2x2 matrix
print(m3)

tensor([[ 58,  64],
        [139, 154]])


In [51]:
m1 = torch.tensor([[1, 2, 3], [4, 5, 6 ], [7, 8, 9]])  # 3x3 matrix
m2 = torch.tensor([[7, 8], [9, 10], [11, 12]]) # 3x2 matrix
m3 = torch.mm(m1, m2)  # 3x2 matrix
print(m3)

tensor([[ 58,  64],
        [139, 154],
        [220, 244]])


In [52]:
m1 = torch.tensor([[1, 2, 3], [4, 5, 6 ]])  # 2x3 matrix
m2 = torch.tensor([[7, 8], [9, 10]]) # 2x2 matrix
m3 = torch.mm(m1, m2)  # It should not work
print(m3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x2)

# n-dimensional tensor

In [61]:
data = [1, 2, 3, 4, 5 , 6, 7, 8]

In [62]:
shape = (2, 2, 2)

In [63]:
n_d_tensor = torch.tensor(data).reshape(shape)
print(n_d_tensor)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [65]:
x = torch.tensor([1, 2, 3])
x_gpu = x.to('cuda')  # Move tensor to GPU

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx